Sign up
F-Jean/SnowTricks pull request #13
Opened 2020-11-23 09:13 UTC by F-Jean

2020-11-23 09:21 UTC, TBoileau requested changes

2020-11-23 09:21 UTC, TBoileau commented on config/packages/security.yaml
>          users_in_memory: { memory: null }
à supprimer

2020-11-23 09:21 UTC, TBoileau commented on src/Controller/SecurityController.php
> +        $form->handleRequest($request);
`$form = $this->createForm(RegisterType::class, $user)->handleRequest($request);`

2020-11-23 09:21 UTC, TBoileau commented on src/Controller/SecurityController.php
> +        return $this->redirectToRoute('security/login.html.twig');
Tu t'es trompé entre redirect et render, la redirection est à faire dans le if après le traitement, et l'affichage en dehors du if

2020-11-23 09:21 UTC, TBoileau commented on src/Entity/User.php
> +     * @Assert\Email()
Assert\NotBlank

2020-11-23 09:21 UTC, TBoileau commented on src/Entity/User.php
> +     * @Assert\Length(min="8", minMessage="Le mot de passe doit faire minimum 8 caractères.")
Assert\NotBlank

2020-11-23 09:21 UTC, TBoileau commented on src/Entity/User.php
> +     * @Assert\Length(min="8", minMessage="Le mot de passe doit faire minimum 8 caractères.")
Assert\Regexp

2020-11-23 09:21 UTC, TBoileau commented on src/Entity/User.php
> +
a supprimer

2020-11-23 09:21 UTC, TBoileau commented on src/Form/RegisterType.php
> +            ))
a supprimer

2020-11-23 09:21 UTC, TBoileau commented on src/Form/RegisterType.php
> +            ->add('confirm_password',    PasswordType::class, array(
à remplacer par un RepeatedType

2020-11-23 09:21 UTC, TBoileau commented on templates/security/register.html.twig
> +        {{ form_row(form.confirm_password) }}
à supprimer

2020-11-30 09:13 UTC, TBoileau requested changes

2020-11-30 09:13 UTC, TBoileau commented on src/Entity/User.php
> +     * )
Supprimer les assertions sur $password

2020-11-30 09:13 UTC, TBoileau commented on src/Form/RegisterType.php
> +            ))
Pour gérer le message d'erreur en cas de non similarité des mots de passe, utiliser l'option `invalid_message`

2020-12-02 15:20 UTC, F-Jean commented on src/Entity/User.php
> +     * )
fait

2020-12-02 15:20 UTC, F-Jean commented on src/Form/RegisterType.php
> +            ))
fait

2020-12-02 15:21 UTC, closed without merging