Show trick
F-Jean/SnowTricks pull request #19
Opened 2021-05-13 17:13 UTC by F-Jean

Dans add_mre_illustrations.js j'ai ajouté du code sous : /* SHOW IMAGE ON SELECT */.
Normalement je pense que ça devrait fonctionner, mais je n'ai pas d'image.
Tu aurais une idée ?

2021-05-17 09:31 UTC, TBoileau requested changes

2021-05-17 09:31 UTC, TBoileau commented on public/js/add_more_illustrations.js
> +    .querySelector("input").onchange = function() {previewFile()};
Essaie d'utiliser le addEventListener
Ensuite, n'oubli pas que comme le remove, quand le DOM n'existe pas, par conséquent les images que tu ajoutes ne seront pas pris en compte dans l'évent

2021-05-19 13:24 UTC, F-Jean commented on public/js/add_more_illustrations.js
> +    .querySelector("input").onchange = function() {previewFile()};
Je ne comprends pas. 
Le DOM qui n'esiste pas au lancement de ma page, c'est l'input de mon {{ form_row(form.file) }} et mon image de <img src="" width="325" height="200">.

Mais à partir du moment ou j'appuie sur le button "btn-new", ces deux éléments sont ajoutés au DOM.
Et je comprenais que venir modifier l'option de mon input grace au .onchange, ça lançait ma previewFile(). Donc au moment ou le JS s'execute mon DOM est présent non ?

2021-05-19 16:18 UTC, TBoileau commented on public/js/add_more_illustrations.js
> +    .querySelector("input").onchange = function() {previewFile()};
non car le JS est chargé dans le navigateur dès qu'il est disponible, au moment ou tu ajoutes une image à ton DOM, le code est déjà pris en charge et par conséquent ton event ne pourra pas fonctionner

2021-05-20 18:34 UTC, F-Jean commented on public/js/add_more_illustrations.js
> +    .querySelector("input").onchange = function() {previewFile()};
je ne sais pas si je comprends de travers mais en fait il faudrait que j'ajoute un addEventListener sur mon input qui au click appelle ma fonction un peu comme ça : 
document
    .querySelectorAll('input')
    .addEventListener("click", previewFile());
Mais le problème est qu'à ce moment la mon input n'existe pas dans le dom et donc n'est pas pris en compte ?

2021-05-21 13:38 UTC, TBoileau commented on public/js/add_more_illustrations.js
> +    .querySelector("input").onchange = function() {previewFile()};
tu le laisses comme il est et tu le doubles au moment ou tu l'ajoutes dans le DOM

2021-07-05 17:42 UTC, closed without merging