Fixtures
F-Jean/SnowTricks pull request #28
Opened 2021-07-31 12:15 UTC by F-Jean

2021-08-03 09:44 UTC, TBoileau requested changes

2021-08-03 09:44 UTC, TBoileau commented on src/DataFixtures/TrickFixtures.php
> +        $categories = array(
```php
$users = [
    'fjean' => (new User())->setUsername('fjean')->setEmail('email@email.com'), 
    'claire' => (new User())->setUsername('claire')->setEmail('email@email.com')
];

foreach ($users as $user) {
   $user->setPassword($this->userEncoder->encodePassword($user, 'password'));
   $manager->persist($user);
}

$categories = [
    'Grab' => [
        ['user' => $users['jfean']]
    ]
];

foreach ($categories as $name => $tricks) {
    foreach ($tricks as $rawTrick) {
          $trick = new Trick();
          $trick->setUser($rawTrick['user']);
    }
}
```

2021-08-03 09:44 UTC, TBoileau commented on src/Controller/TrickController.php
> +        $trick->setSlug($slugger->slug($trick->getName()));
````php
$trick->setSlug($slugger->slug($trick->getName())->lower()->toString());
```

2021-08-03 09:44 UTC, TBoileau commented on templates/homepage/trick.html.twig
> +                <a href="{{ path('trick_delete', {'slug' : trick.slug}) }}" class="btn btn-primary delete-btn"><i class="fas fa-trash-alt"></i></a>
A terme, on ajoutera des voters

2021-08-03 09:44 UTC, TBoileau commented on templates/trick/show.html.twig
>              {% if app.user %}
utiliser le is_granted

2021-08-06 08:35 UTC, TBoileau requested changes

2021-08-06 08:35 UTC, TBoileau commented on src/DataFixtures/TrickFixtures.php
> +                    ]
````php
"comments" => [$comments[ "1"], $comments["2"]]    
```

2021-08-06 08:35 UTC, TBoileau commented on src/DataFixtures/TrickFixtures.php
> +                    ],
`"user" => $users["loic"]`

Tout sur une ligne

2021-08-06 08:35 UTC, TBoileau commented on src/DataFixtures/TrickFixtures.php
>                      ],
`"user" => $users["loic"]`

Tout sur une ligne

2021-08-06 11:17 UTC, F-Jean commented
Modifications effectuées, tout fonctionne

2021-08-06 11:17 UTC, merged