Functional tests
F-Jean/SnowTricks pull request #29
Opened 2021-12-06 11:51 UTC by F-Jean

Tout mes services fonctionnent. J'ai essayé de les clean comme il faut dis moi si tout est ok.

2021-12-06 11:53 UTC, F-Jean commented on public/js/load_more.js
> +                    $('.load').hide();
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/F-Jean/SnowTricks/pullRequest?prid=8521799)
```suggestion
                    $(".load").hide();
```

2021-12-06 11:53 UTC, F-Jean commented on public/js/add_more_illustrations.js
> +    .querySelectorAll('.btn-remove')
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/F-Jean/SnowTricks/pullRequest?prid=8521799)
```suggestion
    .querySelectorAll(".btn-remove")
```

2021-12-13 09:57 UTC, TBoileau requested changes

2021-12-13 09:57 UTC, TBoileau commented on public/js/add_more_illustrations.js
> +    item.querySelector('input[type=file]').addEventListener("change", function() {previewFile(item)});
```js
item.querySelector('input[type=file]').addEventListener("change", () => previewFile(item));
```

2021-12-13 09:57 UTC, TBoileau commented on public/js/load_comments.js
> +            url : '/load_comments/' + trickId + '/' + page,
```js
url : `/load_comments/${trickId}/page`,
```

2021-12-13 09:57 UTC, TBoileau commented on src/Controller/SecurityController.php
> +    public function __construct()
Supprimer le constructeur

2021-12-13 09:57 UTC, TBoileau commented on src/Controller/SecurityController.php
> +        $user;
A supprimer

2021-12-13 09:57 UTC, TBoileau commented on src/Controller/SecurityController.php
> +    public function resetPassword($resetToken, Request $request, ResetPassword $reseter)
Tu peux injecter directement ton `User $user` à la place de `$resetToken`.
Si le token n'existe pas, donc erreur mais ce n'est pas grave.

2021-12-13 09:57 UTC, TBoileau commented on src/Controller/SecurityController.php
> +            $reseter->resetToken($resetToken, $form);
tu ne passes plus `$resetToken` mais un `user`

2021-12-13 09:57 UTC, TBoileau commented on src/Controller/SecurityController.php
>          $form = $this->createForm(ResetPasswordType::class)->handleRequest($request);
Normalement tu aurais du relier le ResetPasswordType avec la classe User

2021-12-13 09:57 UTC, TBoileau commented on src/Controller/SecurityController.php
> +            $reseter->resetToken($resetToken, $form);
A la place de `$form`, tu peux directement envoyer le nouveau mot de passe en clair.

2021-12-13 09:57 UTC, TBoileau commented on src/Service/ResetPassword.php
> +    public function resetToken($resetToken, $form) {
Tu récupères un `User $user, string 
$newPassword`

2021-12-13 09:57 UTC, TBoileau commented on src/Service/ResetPassword.php
> +        }
Inutile

2021-12-13 09:57 UTC, TBoileau commented on src/Service/ResetPassword.php
> +            $form->get('resetPassword')->getData()
A remplacer par `$newPassword`

2021-12-13 09:57 UTC, TBoileau commented on src/Controller/TrickController.php
> +                ->setUser($user);
A mettre au moment ou tu instancies ton Trick (ligne 40).
Tu peux setter ton `addedAt` dans le constructeur de ton entité.

2021-12-13 09:57 UTC, TBoileau commented on src/Controller/TrickController.php
> +                }
````php

if ($this->trickRepository->count(['slug' => $trick->getSlug()]) === 0) {
    // SERVICE AddIllustration
    $illustrator->addIllustration($trick);
    return $this->redirectToRoute('homepage', ['_fragment'=>'content-trick']);
}
$form->get('name')->addError(new FormError('Cette figure existe déjà.'));

```

2021-12-13 09:57 UTC, TBoileau commented on src/Controller/TrickController.php
> +                ->setUser($user);
A supprimer

2021-12-13 09:57 UTC, TBoileau commented on src/Controller/TrickController.php
> +                if($this->trickRepository->count(['slug' => $newSlug]) > 0) {
Mettre les 2 if dans un seul if

2021-12-13 09:57 UTC, TBoileau commented on src/Controller/TrickController.php
> +                } else {
Aurait pu être remplacer par un validator custom

2021-12-13 09:57 UTC, TBoileau commented on src/Service/CreateComment.php
> +            $this->manager->flush();
Attention à l'indentation

2021-12-13 09:57 UTC, TBoileau commented on src/Service/CreateComment.php
> +        $comment->setPostedAt(new \DateTimeImmutable())
On peut set le postedAt dans le constructeur

2021-12-20 10:00 UTC, closed without merging